
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_NAME"] %>
  pool: 5
  host: <%= ENV["END_POINT"] %> 
  username: <%= ENV["USERNAME"] %> 
  password: <%= ENV["PASSWORD"] %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: seat_booking_development
  host: 'localhost'
  username: 'root'
  password: 'rootroot'


test:
  <<: *default
  database: seat_booking_test

production:
  <<: *default
  database: seat_booking_production
  username: seat_booking
  password: <%= ENV['SEAT_BOOKING_DATABASE_PASSWORD'] %>
